### Create user

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "john",
  "name": "Johnny Appleseed",
  "password": "iamfine"
}

### Get user

GET http://localhost:3003/api/users

### Login

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "john",
  "password": "iamfine"
}

### Token is eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjYxMjQ2YWY2OWRkM2RhMDNiOWQ5MGY5ZSIsImlhdCI6MTYyOTc3Njc5Nn0.AOCMxRipUfzZ2gXAIlyViCPQLXfAPq725wjvX2ah3ug

### Failed login

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "john",
  "password": "iamnotfine"
}

### Post blog

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjYxMjQ2YWY2OWRkM2RhMDNiOWQ5MGY5ZSIsImlhdCI6MTYyOTc3Njc5Nn0.AOCMxRipUfzZ2gXAIlyViCPQLXfAPq725wjvX2ah3ug

{
  "title": "My also very First Blog",
  "author": "John Somebody",
  "url": "http://example.com",
  "likes": 1
}

### Post blog without authorization is invalid

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My not so very First Blog",
  "author": "John Someone",
  "url": "http://example.com",
  "likes": 3
}

### Get blogs

GET http://localhost:3003/api/blogs

### Delete (modify URL)

DELETE http://localhost:3003/api/blogs/61246cf19dd3da03b9d90fae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjYxMjQ2YWY2OWRkM2RhMDNiOWQ5MGY5ZSIsImlhdCI6MTYyOTc3Njc5Nn0.AOCMxRipUfzZ2gXAIlyViCPQLXfAPq725wjvX2ah3ug